name: Generate Terraform Docs

on:
  push:
    branches:
      - main
      - IaCTofu
    paths-ignore:
      - "README.md"
      - "infra/modules/**/README.md"
  pull_request:

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Install terraform-docs
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-linux-amd64.tar.gz | tar -xz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate docs for root module
        run: |
          terraform-docs markdown table . --output-file README.md --output-mode inject

      - name: Debug module READMEs before docs
        run: |
          echo "===== VPC README (before) ====="
          cat infra/modules/vpc/README.md || true

          echo "===== EC2 README (before) ====="
          cat infra/modules/ec2/README.md || true

          echo "===== SG README (before) ====="
          cat infra/modules/security_group/README.md || true


      - name: Generate docs for modules
        run: |
          terraform-docs markdown table ./infra/modules/vpc --output-file ./infra/modules/vpc/README.md --output-mode inject
          terraform-docs markdown table ./infra/modules/ec2 --output-file ./infra/modules/ec2/README.md --output-mode inject
          terraform-docs markdown table ./infra/modules/security_group --output-file ./infra/modules/security_group/README.md --output-mode inject

      - name: Debug module READMEs after docs
        run: |
          echo "===== VPC README (after) ====="
          cat infra/modules/vpc/README.md

          echo "===== EC2 README (after) ====="
          cat infra/modules/ec2/README.md
          echo "===== SG README (after) ====="
          cat infra/modules/security_group/README.md

      - name: Commit and push changes
        env:
          IAC_TOKEN: ${{ secrets.IAC_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com" 

          git diff --quiet -- README.md infra/modules/**/README.md || (
            git add README.md infra/modules/**/README.md
            git commit -m "docs: update terraform docs"
            git push https://x-access-token:${IAC_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          )
