name: Generate Terraform Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - IaCTofu
    paths-ignore:
      - "README.md"
      - "infra/modules/**/README.md"
  pull_request:

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Install terraform-docs
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-linux-amd64.tar.gz | tar -xz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate docs for root module
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          output-file: README.md
          output-method: inject
      
      - name: Sleep 10 seconds
        run: sleep 10

      - name: Generate docs for VPC module
        working-directory: infra/modules/vpc
        run: |
          terraform-docs markdown table --config .terraform-docs.yml --output-file README.md --output-mode inject .
          cat README.md

      - name: Generate docs for EC2 module
        working-directory: infra/modules/ec2
        run: |
          terraform-docs markdown table --config .terraform-docs.yml --output-file README.md --output-mode inject .
          cat README.md

      - name: Generate docs for Security Group module
        working-directory: infra/modules/security_group
        run: |
          terraform-docs markdown table --config .terraform-docs.yml --output-file README.md --output-mode inject .
          cat README.md

      - name: Sleep 10 seconds
        run: sleep 10

      - name: Commit and push changes
        env:
          IAC_TOKEN: ${{ secrets.IAC_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md 
          git diff --cached --quiet || git commit -m "docs: update root README"
          git add infra/modules/**/README.md
          git diff --cached --quiet || git commit -m "docs: update module READMEs"
          git push https://x-access-token:${IAC_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}